### ISSUE TITLE
SDL_Joystick Event continuously and erroniously running making it impossible to play. 

### ISSUE THREAD

**Issue by Sapein** [estevaofon/mini-dbz#2]
I can not actually play the game, for the moment that the game begins (after the splash screen) it seems to execute SDL_JoystickGetButton and SDL_JoystickGetAxis. This does it continuously...making it impossible to control the game or even really play it. 

Steps to Reproduce:
1) Cloned from github
2) Run the program

System:
OS: Devuan Jessie 32-bit 
Window Manager: i3 (i3wm)
Python: Python 2.7
Pygame: 1.9.1
Additional Information/Potential Causes: I do have a touchscreen, possibly that's interfering with the game's detection?

**Comment by estevaofon** [comment]
Yes, it is the touchscreen. When no joysticks are detected it doesn't show any output of SDL_Joystick.
I'm going have a look on how to disable the joystick on my code.

**Comment by Sapein** [comment]
Alright. You could probably go about asking the user if there is a joystick that they are using, and if they select yes it accepts joystick input, otherwise it doesn't.  Just an idea.

**Comment by estevaofon** [comment]
Yeah, i will do something like that. I will create a global boolean variable called joystick_enabled, and if it's set to false, it will disable all joystick code. Soon I will push the update.

**Comment by Sapein** [comment]
Thank-you. I really want to try this out, as it's interesting, I would help fix it, but I have no idea where to start.

**Comment by estevaofon** [comment]
You are welcome, I'm glad to help and improve my code! I've made the update. Let's see if it's going to work. After you clone this new version of the project, open the file mini-dbz/scr/main.py and in line 11, set the variable joystick_enabled to False.
Is it working now?

**Comment by Sapein** [comment]
Yup, that fixes the issue! I can now navigate properly!

**Comment by estevaofon** [comment]
Nice! And the gameplay, are you able to play properly?

**Comment by Sapein** [comment]
It seems so (although there seems to be an interesting error relating to the full-screen mode by default)

**Comment by estevaofon** [comment]
Hmn, how is that, what is the error, is there any error output? Does it work ok in window display?

**Comment by Sapein** [comment]
It works fine in Window mode, however here is the output:

```
Traceback (most recent call last):
  File "play.py", line 14, in <module>
    game = main.Main(w, resolution = (1200, 768))
  File "/home/chanku/pygames/github/mini-dbz/src/main.py", line 50, in __init__
    pygame.FULLSCREEN, 32)
pygame.error: No video mode large enough for 1200x768
```

More than likely it's due to me having a smaller monitor. 

I also have a small idea on how to have networked multiplayer, if it's not already included :P

EDIT: We might wanna put this into it's own issue, for organizational purposes :P

**Comment by estevaofon** [comment]
Yeah, you are right, it's cause you monitor isn't very large. In this case, it's better use the window mode, using, python play.py -w. In the play.py you can test some other size of resolution, instead of (1200, 768). Would be nice to have multiplayer! Feel free to contribute :)

**Comment by Sapein** [comment]
Alright. Well Multiplayer would be able to be done one of two ways, both would require async-io. Way 1 uses multi-processing and Way 2 doesn't do that, but implements it directly in the pygame code. 

Multi-processing would be a bit easier in the long run, due to the fact that if the networking hangs then the game itself is still responsive, and networking reading is blocking by default.

**Comment by estevaofon** [comment]
Very interesting, unfortunately for now I don't understand about networking, but I would be glad to merge my project with a multiplayer implementation. As you suggested I will close this issue for organization purposes. Feel free to keep in touch.
